# Generated by Django 5.1.4 on 2025-03-28 12:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("reg_code", models.CharField(blank=True, max_length=250, null=True)),
                ("pilot", models.BooleanField()),
            ],
            options={
                "db_table": "district",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("reg_code", models.CharField(primary_key=True, serialize=False)),
                ("pilot", models.BooleanField()),
            ],
            options={
                "db_table": "region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="assetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("asset_type", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("purchase_date", models.DateField()),
                ("warranty_expiration", models.DateField()),
                ("status", models.BooleanField(default=True)),
                (
                    "asset_type_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.assettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="healthFacilitiesTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("facility_name", models.CharField(max_length=24)),
                ("no_of_commuities", models.IntegerField()),
                ("name_of_incharge", models.IntegerField()),
                ("contact_of_incharge", models.CharField()),
                ("longitude", models.FloatField(max_length=10)),
                ("latitude", models.FloatField(max_length=10)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "district_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.districts",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="cwcScheduleTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("cwc_type", models.CharField(max_length=24)),
                ("date", models.DateField(max_length=24)),
                (
                    "healthFacilitiesTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.healthfacilitiestbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="communityTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("Community", models.CharField(max_length=24)),
                ("population", models.IntegerField()),
                (
                    "healthFacilitiesTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.healthfacilitiestbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="assetFacilityassignementTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                (
                    "assetTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.asset"
                    ),
                ),
                (
                    "healthFacilitiesTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.healthfacilitiestbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="healthWorkersTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("hw_name", models.CharField(max_length=240)),
                ("designation", models.CharField(max_length=54)),
                ("hw_contact", models.CharField(max_length=10)),
                (
                    "healthFacilitiesTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.healthfacilitiestbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="staffTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("gender", models.CharField(max_length=250)),
                ("contact", models.CharField(max_length=250)),
                ("email_address", models.EmailField(blank=True, max_length=250)),
                ("uid", models.CharField(blank=True, max_length=2500, null=True)),
                ("district", models.CharField(blank=True, max_length=250, null=True)),
                ("staffid", models.CharField(blank=True, max_length=250, null=True)),
                ("mpassword", models.CharField(default="P@ssw0rd24", max_length=250)),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Details",
            },
        ),
        migrations.CreateModel(
            name="regionStaffTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                (
                    "region_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.region"
                    ),
                ),
                (
                    "staffTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.stafftbl",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Region Assignments",
            },
        ),
        migrations.CreateModel(
            name="districtStaffTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                (
                    "district_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.districts",
                    ),
                ),
                (
                    "staffTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.stafftbl",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff District Assignments",
            },
        ),
        migrations.CreateModel(
            name="assetSaffassignementTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                (
                    "assetTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.asset"
                    ),
                ),
                (
                    "staffTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.stafftbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
