# Generated by Django 5.1.4 on 2025-03-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="districts",
            options={"managed": True},
        ),
    ]
