# Generated by Django 5.1.4 on 2025-03-28 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_districts_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="districts",
            name="reg_code",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.region",
            ),
            preserve_default=False,
        ),
    ]
