# Generated by Django 5.1.4 on 2025-03-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_rename_district_foreignkey_healthfacilitiestbl_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="name_of_incharge",
            field=models.CharField(),
        ),
    ]
