# Generated by Django 5.1.4 on 2025-03-31 05:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_alter_healthfacilitiestbl_name_of_incharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
