# Generated by Django 5.1.4 on 2025-03-31 08:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_healthfacilitiestbl_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="cwcscheduletbl",
            name="cwc_category",
            field=models.CharField(
                choices=[("Heavy", "Heavy"), ("Normal", "Normal")],
                default="Normal",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_type",
            field=models.CharField(
                choices=[("Static", "Static"), ("Outright", "Outright")], max_length=24
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
