# Generated by Django 5.1.4 on 2025-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_cwcscheduletbl_cwc_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"managed": True},
        ),
    ]
