# Generated by Django 5.1.4 on 2025-04-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_alter_region_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districts",
            name="region",
        ),
        migrations.AddField(
            model_name="districts",
            name="reg_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
