# Generated by Django 5.1.4 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_districts_district_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(default="na", max_length=24),
        ),
        migrations.AddField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(default="na", max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_name",
            field=models.CharField(default="na", max_length=24),
        ),
    ]
