# Generated by Django 5.1.4 on 2025-04-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_healthfacilitiestbl_facility_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthfacilitiestbl",
            old_name="point",
            new_name="geom",
        ),
    ]
