# Generated by Django 5.1.4 on 2025-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_rename_point_healthfacilitiestbl_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("health_centre", "Health Centre"),
                    ("chps_compound", "CHPS Compound"),
                    ("polyclinic", "Polyclinic"),
                    ("maternity_home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                ],
                default="na",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private_facility", "Private Facility"),
                    ("chag", "CHAG"),
                ],
                max_length=24,
            ),
        ),
    ]
