# Generated by Django 5.1.4 on 2025-04-12 10:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_alter_healthfacilitiestbl_facility_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                ],
                default="na",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
