# Generated by Django 5.1.4 on 2025-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_alter_healthfacilitiestbl_facility_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="contact_of_incharge",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_name",
            field=models.CharField(default="na", max_length=240),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                ],
                default="na",
                max_length=240,
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="latitude",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="longitude",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="name_of_incharge",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="no_of_commuities",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private_facility", "Private Facility"),
                    ("chag", "CHAG"),
                ],
                max_length=240,
            ),
        ),
    ]
