# Generated by Django 5.1.4 on 2025-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_alter_healthfacilitiestbl_contact_of_incharge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_name",
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                ],
                max_length=240,
            ),
        ),
    ]
