# Generated by Django 5.1.4 on 2025-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0018_alter_healthfacilitiestbl_facility_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthworkerstbl",
            name="etracker_trained",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                    ("Clinic", "Clinic"),
                ],
                max_length=240,
            ),
        ),
    ]
