# Generated by Django 5.1.4 on 2025-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0019_healthworkerstbl_etracker_trained_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_type",
            field=models.CharField(
                choices=[("Static", "Static"), ("Outreach", "Outreach")], max_length=24
            ),
        ),
    ]
