# Generated by Django 5.1.4 on 2025-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0020_alter_cwcscheduletbl_cwc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="pcreportTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("name_of_pc", models.CharField(blank=True, max_length=24)),
                ("reporting_date", models.CharField(blank=True, max_length=24)),
                ("district", models.CharField(blank=True, max_length=24)),
                ("hf_name", models.CharField(blank=True, max_length=24)),
                ("hf_coodinates", models.CharField(blank=True, max_length=24)),
                ("new_registrants", models.CharField(blank=True, max_length=24)),
                ("tablets_functional", models.CharField(blank=True, max_length=24)),
                ("issue_with_tablet", models.CharField(blank=True, max_length=24)),
                ("scanners_functional", models.CharField(blank=True, max_length=24)),
                ("issue_with_scanner", models.CharField(blank=True, max_length=24)),
                (
                    "hw_concern_about_etracker",
                    models.CharField(blank=True, max_length=24),
                ),
                ("hw_concern", models.CharField(blank=True, max_length=24)),
                (
                    "hw_concern_about_biometrics",
                    models.CharField(blank=True, max_length=24),
                ),
                ("hw_concern_biometric", models.CharField(blank=True, max_length=24)),
                ("clients_have_issues", models.CharField(blank=True, max_length=24)),
                ("client_issue", models.CharField(blank=True, max_length=24)),
                ("positive_feedback", models.CharField(blank=True, max_length=24)),
                ("hw_positive_feedback", models.CharField(blank=True, max_length=24)),
                ("feedback_comment", models.CharField(blank=True, max_length=24)),
                ("recommendation", models.CharField(blank=True, max_length=24)),
                ("SubmissionDate", models.CharField(blank=True, max_length=24)),
                ("uid", models.CharField(blank=True, max_length=24)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
