# Generated by Django 5.1.4 on 2025-04-19 06:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0021_pcreporttbl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="hf_coodinates",
        ),
        migrations.AddField(
            model_name="pcreporttbl",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="pcreporttbl",
            name="hf_coodinates_lat",
            field=models.FloatField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcreporttbl",
            name="hf_coodinates_lng",
            field=models.FloatField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community_leader_contact",
            field=models.CharField(blank=True, default="Not available", max_length=200),
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community_leader_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_category",
            field=models.CharField(
                choices=[("Heavy", "Heavy"), ("Normal", "Normal")],
                default="Normal",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_type",
            field=models.CharField(
                choices=[("Static", "Static"), ("Outreach", "Outreach")], max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="date",
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_name",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                    ("Clinic", "Clinic"),
                ],
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private_facility", "Private Facility"),
                    ("chag", "CHAG"),
                ],
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="healthworkerstbl",
            name="hw_name",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="SubmissionDate",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="client_issue",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="clients_have_issues",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="district",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="feedback_comment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hf_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_about_biometrics",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_about_etracker",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_biometric",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_positive_feedback",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="issue_with_scanner",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="issue_with_tablet",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="name_of_pc",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="new_registrants",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="positive_feedback",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="recommendation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="reporting_date",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="scanners_functional",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="tablets_functional",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="uid",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="stafftbl",
            name="mpassword",
            field=models.CharField(default="P@ssw0rd200", max_length=250),
        ),
        migrations.CreateModel(
            name="client_issueTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("client_issue", models.CharField(blank=True, max_length=200)),
                (
                    "pcreportTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.pcreporttbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="hw_concern_biometricTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("hw_concern_biometric", models.CharField(blank=True, max_length=200)),
                (
                    "pcreportTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.pcreporttbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="hw_concernTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("hw_concern", models.CharField(blank=True, max_length=200)),
                (
                    "pcreportTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.pcreporttbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="issuewithscannerTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("issue_with_scanner", models.CharField(blank=True, max_length=200)),
                (
                    "pcreportTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.pcreporttbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="tabletissueTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("delete_field", models.CharField(default="no", max_length=10)),
                ("tablet_issue", models.CharField(blank=True, max_length=200)),
                (
                    "pcreportTbl_foreignkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.pcreporttbl",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
