# Generated by Django 5.1.4 on 2025-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0022_remove_pcreporttbl_hf_coodinates_pcreporttbl_geom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_issuetbl",
            name="client_issue",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community_leader_contact",
            field=models.CharField(blank=True, default="Not available", max_length=500),
        ),
        migrations.AlterField(
            model_name="communitytbl",
            name="community_leader_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_category",
            field=models.CharField(
                choices=[("Heavy", "Heavy"), ("Normal", "Normal")],
                default="Normal",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="cwc_type",
            field=models.CharField(
                choices=[("Static", "Static"), ("Outreach", "Outreach")], max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="cwcscheduletbl",
            name="date",
            field=models.DateField(max_length=500),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_name",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Health Centre", "Health Centre"),
                    ("CHPS Compound", "CHPS Compound"),
                    ("Polyclinic", "Polyclinic"),
                    ("Maternity Home", "Maternity Home"),
                    ("Hospital", "Hospital"),
                    ("Clinic", "Clinic"),
                ],
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private_facility", "Private Facility"),
                    ("chag", "CHAG"),
                ],
                max_length=5000,
            ),
        ),
        migrations.AlterField(
            model_name="healthworkerstbl",
            name="hw_name",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="hw_concern_biometrictbl",
            name="hw_concern_biometric",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="hw_concerntbl",
            name="hw_concern",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="issuewithscannertbl",
            name="issue_with_scanner",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="SubmissionDate",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="client_issue",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="clients_have_issues",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="district",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="feedback_comment",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hf_coodinates_lat",
            field=models.FloatField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hf_coodinates_lng",
            field=models.FloatField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hf_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_about_biometrics",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_about_etracker",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_concern_biometric",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="hw_positive_feedback",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="issue_with_scanner",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="issue_with_tablet",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="name_of_pc",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="new_registrants",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="positive_feedback",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="recommendation",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="reporting_date",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="scanners_functional",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="tablets_functional",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="uid",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="stafftbl",
            name="mpassword",
            field=models.CharField(default="P@ssw0rd500", max_length=250),
        ),
        migrations.AlterField(
            model_name="tabletissuetbl",
            name="tablet_issue",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
