# Generated by Django 5.1.4 on 2025-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0023_alter_client_issuetbl_client_issue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcreporttbl",
            name="feedback_comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="pcreporttbl",
            name="recommendation",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
