# Generated by Django 5.1.4 on 2025-04-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0025_alter_client_issuetbl_client_issue_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="client_issueTbl",
            new_name="pc_client_issueTbl",
        ),
        migrations.RenameModel(
            old_name="hw_concernTbl",
            new_name="pc_hw_concern_biometricTbl",
        ),
        migrations.RenameModel(
            old_name="hw_concern_biometricTbl",
            new_name="pc_hw_concernTbl",
        ),
        migrations.RenameModel(
            old_name="issuewithscannerTbl",
            new_name="pc_issuewithscannerTbl",
        ),
        migrations.RenameModel(
            old_name="tabletissueTbl",
            new_name="pc_tabletissueTbl",
        ),
        migrations.RenameField(
            model_name="pc_hw_concern_biometrictbl",
            old_name="hw_concern",
            new_name="hw_concern_biometric",
        ),
        migrations.RenameField(
            model_name="pc_hw_concerntbl",
            old_name="hw_concern_biometric",
            new_name="hw_concern",
        ),
    ]
