# Generated by Django 5.1.4 on 2025-04-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0026_rename_client_issuetbl_pc_client_issuetbl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="client_issue",
        ),
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="hw_concern",
        ),
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="hw_concern_biometric",
        ),
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="issue_with_scanner",
        ),
        migrations.RemoveField(
            model_name="pcreporttbl",
            name="issue_with_tablet",
        ),
    ]
