# Generated by Django 5.1.4 on 2025-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0027_remove_pcreporttbl_client_issue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcreporttbl",
            name="reporting_date",
            field=models.DateField(blank=True, max_length=2000),
        ),
    ]
