# Generated by Django 5.1.4 on 2025-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0028_alter_pcreporttbl_reporting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthfacilitiestbl",
            name="ownership",
            field=models.CharField(max_length=20000),
        ),
    ]
